# Config file for automatic testing at travis-ci.com

language: python
dist: xenial
python:
  - 3.7

env:
  - CODECOV_TOKEN=aea0a4e9-6aa6-4216-a67e-55a14e402e2c

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install: pip install -U tox-travis
install: pip install -r requirements/test.txt

# Command to run tests, e.g. python setup.py test
script: tox

after_success:
  - codecov

# deploy:
  # provider: pypi
  # user: "__token__"
  # TODO: ENCRYPT TOKEN
  # distributions: "sdist bdist_wheel"
  # on:
    # tags: true
    # branch: master

